config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'dashboard#index'

  resources :contact, :ticket
  resources :users, :items

  resources :projects
  resources :eworker
  resources :csvlocations



  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  get "/dl" => "ticket#dl", as: :download

  get '/slack' => "slack#index"

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/csvlocation.rb
class Csvlocation < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  has_many :links
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
  has_many :items
  has_many :links
  has_many :projects
  has_many :csvlocations

  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @inbox = mailbox.inbox
    @active = :inbox
    @unread_conversations = []

    @inbox.each do | mail |
      if mail.is_unread?(current_user)
        @unread_conversations << mail
      end
    end

    @unread = mailbox.inbox(:unread => true).count
    @level_1 = Ticket.where( "level = '1'" ).length
    @level_2 = Ticket.where( "level = '2'" ).length
    @level_3 = Ticket.where( "level = '3'" ).length
    @not_viewed = Ticket.where( "viewed = false" ).length
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ticket_number = Ticket.last.ticket_number.to_i + 1
    @ticket_number = @ticket_number.to_s
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end

  def find_me( email )
    me = USERS.select { |obj| obj[ 'profile' ][ 'email' ] == email }

    if me.empty?
      return false
    else
      my_picture = me.first[ 'profile' ][ 'image_192' ]
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/csvlocation_helper.rb
module CsvlocationHelper
end

app/helpers/eworker_helper.rb
module EworkerHelper
  def compare_pb
    billing_ndc_duplicates = {}
    purchasing_ndc_duplicates = {}
    found = {}

    CSV.foreach( 'billing.csv', headers:true, :header_converters=> lambda { | f | f.strip }, :converters=> lambda { | f | f ? f.strip : nil } ) do | billing |
      if billing[ "CLASS" ].to_i > 0
        if billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ]
          billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ][ 5 ] += billing[ "QUANT" ].to_i
          billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ][ 4 ] += billing[ "TotalInsPaid" ].to_f
        else
          billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ] = [ billing[ "DRGNAME" ], billing[ "DRUGSTRONG" ], billing[ "PACKAGESIZE" ], billing[ "CLASS" ], billing[ "TotalInsPaid" ].to_f, billing[ "QUANT" ].to_i ]
        end
      end
    end

    billing_ndc_duplicates.each { | k,v | v[ 4 ] = v[ 4 ].round( 2 ) }


    CSV.foreach( 'purchasing.csv', headers:true, :header_converters=> lambda { | f | f.strip }, :converters=> lambda { | f | f ? f.strip : nil } ) do | purchasing |
      if purchasing_ndc_duplicates[ purchasing[ "Universal Ndc #" ] ]
        purchasing_ndc_duplicates[ purchasing[ "Universal Ndc #" ] ][ 3 ] += purchasing[ "Quantity Billed" ].to_i
      else
        purchasing_ndc_duplicates[ purchasing[ "Universal Ndc #" ] ] = [ purchasing[ "Item Description" ], purchasing[ "Item Type" ], purchasing[ "Size" ].to_i, purchasing[ "Quantity Billed" ].to_i ]
      end
    end

    purchasing_ndc_duplicates.each do | k, v |
      v << v[ 2 ] * v[ 3 ]
      v.delete_at( 2 )
      v.delete_at( 2 )
    end

    billing_ndc_duplicates.each do | ndc, arr |
      purchasing_ndc_duplicates.each do | ndc2, arr2 |
        if ndc.gsub( /(^|[^0-9])0+/, "" ) == ndc2
          complete = arr.insert( 5, arr2[ 2 ] )
          complete = complete.insert( 0, ndc )
          found[ ndc ] = complete
        end
      end
    end

    CSV.open( "file.csv", "wb", :write_headers=> true, :headers => [ "NDC", "Drug Name", "Drug Strength", "Package Size", "Control", "Total Ins. Paid", "Total Units Purchased", "Total Units Billed" ] ) do | csv |
      found.each do | ndc, arr |
        csv << arr
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    # mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/slack_helper.rb
module SlackHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
  def dropbox
    Dropbox::API::Config.app_key = ENV[ "DROPBOX_APP_KEY" ]
    Dropbox::API::Config.app_secret = ENV[ "DROPBOX_SECRET_KEY" ]
    Dropbox::API::Config.mode = "dropbox"
    @client = Dropbox::API::Client.new( :token  => ENV[ "DROPBOX_TOKEN" ], :secret => ENV[ "DROPBOX_SECRET_TOKEN" ] )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_admin_top.html.erb
<div class="row top-panel-admin">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
        <div class="panel panel-bd">
            <div class="panel-body">
                <div class="statistic-box">
                    <h2><span class="count-number"><%= @level_1 %></span> <span class="slight"></span></h2>
                    <div class="small"> Level 1 Tickets</div>
                    <div class="sparkline1 text-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
        <div class="panel panel-bd">
            <div class="panel-body">
                <div class="statistic-box">
                    <h2><span class="count-number"><%= @level_2 %></span> <span class="slight"></span></h2>
                    <div class="small"> Level 2 Tickets</div>
                    <div class="sparkline1 text-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
        <div class="panel panel-bd">
            <div class="panel-body">
                <div class="statistic-box">
                    <h2><span class="count-number"><%= @level_3 %></span> <span class="slight"></span></h2>
                    <div class="small"> Level 3 Tickets</div>
                    <div class="sparkline1 text-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
        <div class="panel panel-bd">
            <div class="panel-body">
                <div class="statistic-box">
                    <h2><span class="count-number"><%= @not_viewed %></span> <span class="slight"></span></h2>
                    <div class="small"> New Tickets</div>
                    <div class="sparkline1 text-center"></div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/dashboard/_header.erb
<header class="main-header">
    <%= link_to( root_path, class: "logo" ) do %>
      <span class="logo-lg">
        <%= image_tag "logo.png" %>
      </span>
    <% end %>

    <%= link_to( root_path, class: "logo cure-logo" ) do %>
      <span class="logo-lg">
        <%= image_tag "logo-cure.png" %>
      </span>
    <% end %>
</header>

<aside class="main-sidebar">
    <!-- sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel text-center">
            <div class="image">
              <% if current_user.picture_url != "" %>
                <img class="img-circle" src="<%= current_user.picture_url %>">
              <% else %>
                <%= image_tag "avatar.png", class: 'img-circle' %>
              <% end %>
            </div>
            <div class="info">
                <p><%= current_user.full_name %></p>
                <%= link_to "Change Avatar", edit_user_path( current_user ), class: "change-avatar-link" %>
                <a href="/slack" class="change-avatar-link slack-link">Link Your Slack Avatar</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form> <!-- /.search form -->
        <!-- sidebar menu -->
        <%= render 'dashboard/nav' %>
    </div> <!-- /.sidebar -->
</aside>

app/views/dashboard/_message_widget.html.erb
<div class="message_widgets">
  <% @unread_conversations.each do | mail | %>
    <%= link_to( conversation_path( mail ) ) do %>
      <div class="inbox-item">
        <div class="inbox-item-img">
          <% if mail.recipients.select { |obj| obj != current_user }.empty? %>
            <%= image_tag "avatar.png", class: "img-circle" %>
          <% elsif mail.recipients.select { |obj| obj != current_user }[ 0 ].picture_url != "" %>
            <img src="<%= mail.recipients.select { |obj| obj != current_user }[ 0 ].picture_url %>" alt="">
          <% else %>
            <%= image_tag "avatar.png", class: "img-circle" %>
          <% end %>
        </div>
        <strong class="inbox-item-author"><%= mailbox.inbox.first.recipients.select { |message| message.full_name != current_user.full_name }[ 0 ].full_name %></strong>
        <p class="inbox-item-text">Subject: <%= mail.subject %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/dashboard/_nav.html.erb
<ul class="sidebar-menu">
    <li class="header">MAIN NAVIGATION</li>

    <li class="active">
      <%= link_to( root_path ) do %>
        <i class="ti-home"></i> <span>Dashboard</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( mailbox_inbox_path ) do %>
      <i class="ti-email"></i> <span>Mail</span>
      <span class="pull-right-container">
        <% if @unread > 0 %>
        <small class="label pull-right bg-red"><%= @unread %></small>
        <% else %>
        <i class="fa fa-angle-left pull-right"></i>
        <% end %>
      </span>
      <% end %>
    </li>

    <!-- <li>
      <%= link_to( ticket_index_path ) do %>
        <i class="ti-layout"></i> <span>My Tickets</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li> -->


    <li>
      <%= link_to( items_path ) do %>
        <i class="fa fa-globe"></i> <span>Order Supplies</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( projects_path ) do %>
        <i class="ti-layout"></i> <span>IT Projects</span>
        <span class="pull-right-container">
          <i class=" fa fa-angle-left pull-right "></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( eworker_index_path ) do %>
        <i class="ti-layout"></i> <span>Excel Worker</span>
        <span class="pull-right-container">
          <i class=" fa fa-angle-left pull-right "></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( destroy_user_session_path, :method => 'delete' ) do %>
        <i class="fa fa-sign-out"></i> <span>Log Out</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li class="header">LABELS</li>
    <li><a href="#"><i class="fa fa-circle color-green"></i> <span>Important</span></a></li>
    <li><a href="#"><i class="fa fa-circle color-red"></i> <span>Warning</span></a></li>
    <li><a href="#"><i class="fa fa-circle color-yellow"></i> <span>Information</span></a></li>
</ul>

app/views/dashboard/_widget_list.html.erb
<ul>
    <li>
        <div class="fb_inner">
            <i class="fa fa-facebook"></i>
            <span class="sc-num">5,791</span>
            <small>Fans</small>
        </div>
    </li>
    <li>
        <div class="twitter_inner">
            <i class="fa fa-twitter"></i>
            <span class="sc-num">691</span>
            <small>Followers</small>
        </div>
    </li>
    <li>
        <div class="g_plus_inner">
            <i class="fa fa-google-plus"></i>
            <span class="sc-num">147</span>
            <small>Followers</small>
        </div>
    </li>
    <li>
        <div class="dribble_inner">
            <i class="fa fa-dribbble"></i>
            <span class="sc-num">3,485</span>
            <small>Followers</small>
        </div>
    </li>
</ul>

app/views/dashboard/index.html.erb
<!-- Site wrapper -->
<div class="wrapper">
    <%= render 'dashboard/header' %>

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <%= render 'layouts/content_header' %>
        <!-- Main content -->
        <section class="content">
          <% if current_user.admin %>
            <%= render 'dashboard/admin_top' %>
          <% end %>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
                    <div class="panel panel-bd lobidisable">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h4>Messages</h4>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="message_inner">
                                <%= render 'message_widget' %>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- calender -->
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
                    <div class="panel panel-bd lobidisable">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h4>Calender</h4>
                            </div>
                        </div>
                        <div class="panel-body">
                            <!-- monthly calender -->
                            <div class="monthly_calender">
                                <div class="monthly" id="m_calendar"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-md-6 col-lg-4 hidden-sm hidden-md">
                    <div class="social-widget">
                        <%= render 'widget_list' %>
                    </div>
                </div>
            </div> <!-- /.row -->
        </section> <!-- /.content -->
    </div> <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
</div>
<!-- ./wrapper -->
<%= javascript_include_tag 'lobipanel.min.js' %>
<script>
  "use strict"; // Start of use strict

  // notification
  setTimeout(function () {
      toastr.options = {
          closeButton: true,
          progressBar: true,
          showMethod: 'slideDown',
          timeOut: 4000
//                        positionClass: "toast-top-left"
      };
      toastr.success('QuickRx Ticket System', 'Welcome To');

  }, 1300);

  //counter
  $('.count-number').counterUp({
      delay: 10,
      time: 5000
  });

  //Chat list
  $('.chat_list').slimScroll({
      size: '3px',
      height: '305px'
  });

  // Message
  $('.message_inner').slimScroll({
      size: '3px',
      height: '320px'
//                    position: 'left'
  });

  //emojionearea
  $(".emojionearea").emojioneArea({
      pickerPosition: "top",
      tonesStyle: "radio"
  });

  //monthly calender
  $('#m_calendar').monthly({
      mode: 'event',
      //jsonUrl: 'events.json',
      //dataType: 'json'
      xmlUrl: 'events.xml'
  });

  //Sparklines Charts
  $('.sparkline1').sparkline([4, 6, 7, 7, 4, 3, 2, 4, 6, 7, 4, 6, 7, 7, 4, 3, 2, 4, 6, 7, 7, 4, 3, 1, 5, 7, 6, 6, 5, 5, 4, 4, 3, 3, 4, 4, 5], {
      type: 'bar',
      barColor: '#37a000',
      height: '35',
      barWidth: '3',
      barSpacing: 2
  });

  $(".sparkline2").sparkline([-8, 2, 4, 3, 5, 4, 3, 5, 5, 6, 3, 9, 7, 3, 5, 6, 9, 5, 6, 7, 2, 3, 9, 6, 6, 7, 8, 10, 15, 16, 17, 15], {
      type: 'line',
      height: '35',
      width: '100%',
      lineColor: '#37a000',
      fillColor: '#fff'
  });

  $(".sparkline3").sparkline([2, 5, 3, 7, 5, 10, 3, 6, 5, 7], {
      type: 'line',
      height: '35',
      width: '100%',
      lineColor: '#37a000',
      fillColor: '#fff'
  });

  $(".sparkline4").sparkline([10, 34, 13, 33, 35, 24, 32, 24, 52, 35], {
      type: 'line',
      height: '35',
      width: '100%',
      lineColor: '#37a000',
      fillColor: 'rgba(55, 160, 0, 0.7)'
  });

  $(".sparkline5").sparkline([4, 2], {
      type: 'pie',
      sliceColors: ['#37a000', '#2c3136']
  });

  $(".sparkline6").sparkline([3, 2], {
      type: 'pie',
      sliceColors: ['#37a000', '#2c3136']
  });

  $(".sparkline7").sparkline([4, 1], {
      type: 'pie',
      sliceColors: ['#37a000', '#2c3136']
  });

  $(".sparkline8").sparkline([1, 3], {
      type: 'pie',
      sliceColors: ['#37a000', '#2c3136']
  });

  $(".sparkline9").sparkline([3, 5], {
      type: 'pie',
      sliceColors: ['#37a000', '#2c3136']
  });
</script>