config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'dashboard#index'

  resources :contact, :ticket
  resources :users, :items

  resources :projects
  resources :eworker
  resources :csvlocations



  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  get "/dl" => "ticket#dl", as: :download

  get '/slack' => "slack#index"

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/csvlocation.rb
class Csvlocation < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  has_many :links
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
  has_many :items
  has_many :links
  has_many :projects
  has_many :csvlocations

  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @unread = mailbox.inbox(:unread => true).count
  end

  def create
    @unread = mailbox.inbox(:unread => true).count
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    name = conversation.recipients.select { |obj| obj != current_user }[ 0 ].full_name
    email = conversation.recipients.select { |obj| obj != current_user }[ 0 ].email
    NotificationMailer.new_notification( name, email ).deliver_now
    redirect_to conversation_path(conversation)
  end

  def show
    if params[ "sent" ]
      @tagger = true
    end

    @unread = mailbox.inbox(:unread => true).count
    @receipts = conversation.receipts_for(current_user).reverse
    # mark conversation as read
    conversation.mark_as_read(current_user)
    @receipts = @receipts.sort_by {|item| item.created_at}
  end

  def reply
    @unread = mailbox.inbox(:unread => true).count
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    name = conversation.recipients.select { |obj| obj != current_user }[ 0 ].full_name
    email = conversation.recipients.select { |obj| obj != current_user }[ 0 ].email
    NotificationMailer.new_notification( name, email ).deliver_now
    redirect_to conversation_path(conversation)
  end

  def trash
    @unread = mailbox.inbox(:unread => true).count
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    @unread = mailbox.inbox(:unread => true).count
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end


  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body, :recipients)
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ticket_number = Ticket.last.ticket_number.to_i + 1
    @ticket_number = @ticket_number.to_s
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end

  def find_me( email )
    me = USERS.select { |obj| obj[ 'profile' ][ 'email' ] == email }

    if me.empty?
      return false
    else
      my_picture = me.first[ 'profile' ][ 'image_192' ]
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/csvlocation_helper.rb
module CsvlocationHelper
end

app/helpers/eworker_helper.rb
module EworkerHelper
  def compare_pb
    billing_ndc_duplicates = {}
    purchasing_ndc_duplicates = {}
    found = {}

    CSV.foreach( 'billing.csv', headers:true, :header_converters=> lambda { | f | f.strip }, :converters=> lambda { | f | f ? f.strip : nil } ) do | billing |
      if billing[ "CLASS" ].to_i > 0
        if billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ]
          billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ][ 5 ] += billing[ "QUANT" ].to_i
          billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ][ 4 ] += billing[ "TotalInsPaid" ].to_f
        else
          billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ] = [ billing[ "DRGNAME" ], billing[ "DRUGSTRONG" ], billing[ "PACKAGESIZE" ], billing[ "CLASS" ], billing[ "TotalInsPaid" ].to_f, billing[ "QUANT" ].to_i ]
        end
      end
    end

    billing_ndc_duplicates.each { | k,v | v[ 4 ] = v[ 4 ].round( 2 ) }


    CSV.foreach( 'purchasing.csv', headers:true, :header_converters=> lambda { | f | f.strip }, :converters=> lambda { | f | f ? f.strip : nil } ) do | purchasing |
      if purchasing_ndc_duplicates[ purchasing[ "Universal Ndc #" ] ]
        purchasing_ndc_duplicates[ purchasing[ "Universal Ndc #" ] ][ 3 ] += purchasing[ "Quantity Billed" ].to_i
      else
        purchasing_ndc_duplicates[ purchasing[ "Universal Ndc #" ] ] = [ purchasing[ "Item Description" ], purchasing[ "Item Type" ], purchasing[ "Size" ].to_i, purchasing[ "Quantity Billed" ].to_i ]
      end
    end

    purchasing_ndc_duplicates.each do | k, v |
      v << v[ 2 ] * v[ 3 ]
      v.delete_at( 2 )
      v.delete_at( 2 )
    end

    billing_ndc_duplicates.each do | ndc, arr |
      purchasing_ndc_duplicates.each do | ndc2, arr2 |
        if ndc.gsub( /(^|[^0-9])0+/, "" ) == ndc2
          complete = arr.insert( 5, arr2[ 2 ] )
          complete = complete.insert( 0, ndc )
          found[ ndc ] = complete
        end
      end
    end

    CSV.open( "file.csv", "wb", :write_headers=> true, :headers => [ "NDC", "Drug Name", "Drug Strength", "Package Size", "Control", "Total Ins. Paid", "Total Units Purchased", "Total Units Billed" ] ) do | csv |
      found.each do | ndc, arr |
        csv << arr
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    # mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/slack_helper.rb
module SlackHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
  def dropbox
    Dropbox::API::Config.app_key = ENV[ "DROPBOX_APP_KEY" ]
    Dropbox::API::Config.app_secret = ENV[ "DROPBOX_SECRET_KEY" ]
    Dropbox::API::Config.mode = "dropbox"
    @client = Dropbox::API::Client.new( :token  => ENV[ "DROPBOX_TOKEN" ], :secret => ENV[ "DROPBOX_SECRET_TOKEN" ] )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.full_name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.full_name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_header.html.erb
<header class="main-header">
  <%= link_to( root_path, class: "logo" ) do %>
    <span class="logo-lg">
      <%= image_tag "logo.png" %>
    </span>
  <% end %>

  <%= link_to( root_path, class: "logo cure-logo" ) do %>
    <span class="logo-lg">
      <%= image_tag "logo-cure.png" %>
    </span>
  <% end %>
</header>

<aside class="main-sidebar">
    <!-- sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel text-center">
          <div class="image">
            <% if current_user.picture_url != "" %>
              <img class="img-circle" src="<%= current_user.picture_url %>">
            <% else %>
              <%= image_tag "avatar.png", class: 'img-circle' %>
            <% end %>
          </div>
            <div class="info">
                <p><%= current_user.full_name %></p>
                <%= link_to "Change Avatar", edit_user_path( current_user ), class: "change-avatar-link" %>
                <a href="/slack" class="change-avatar-link slack-link">Link Your Slack Avatar</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form> <!-- /.search form -->
        <!-- sidebar menu -->
        <%= render 'conversations/nav' %>
    </div> <!-- /.sidebar -->
</aside>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.full_name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/_nav.html.erb
<ul class="sidebar-menu">
    <li class="header">MAIN NAVIGATION</li>

    <li>
      <%= link_to( root_path ) do %>
        <i class="ti-home"></i> <span>Dashboard</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li class="active">
      <%= link_to( mailbox_inbox_path ) do %>
      <i class="ti-email"></i> <span>Mail</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
      <% end %>
    </li>

    <!-- <li>
      <%= link_to( ticket_index_path ) do %>
        <i class="ti-layout"></i> <span>My Tickets</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li> -->

    <li>
      <%= link_to( items_path ) do %>
        <i class="fa fa-globe"></i> <span>Order Supplies</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( eworker_index_path ) do %>
        <i class="ti-layout"></i> <span>Excel Worker</span>
        <span class="pull-right-container">
          <i class=" fa fa-angle-left pull-right "></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( destroy_user_session_path, :method => 'delete' ) do %>
        <i class="fa fa-sign-out"></i> <span>Log Out</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li class="header">LABELS</li>
    <li><a href="#"><i class="fa fa-circle color-green"></i> <span>Important</span></a></li>
    <li><a href="#"><i class="fa fa-circle color-red"></i> <span>Warning</span></a></li>
    <li><a href="#"><i class="fa fa-circle color-yellow"></i> <span>Information</span></a></li>
</ul>

app/views/conversations/new.html.erb
<div class="wrapper">
  <%= render 'conversations/header' %>
  <div class="content-wrapper">
      <%= render 'layouts/content_header' %>
      <section class="content">
          <div class="row">
              <div class="col-sm-12">
                  <div class="mailbox">
                      <div class="mailbox-header">
                          <div class="row">
                              <div class="col-xs-4">
                                  <div class="inbox-avatar">
                                      <% if current_user.picture_url != "" %>
                                        <img class="img-circle border-green" src="<%= current_user.picture_url %>">
                                      <% else %>
                                        <%= image_tag 'avatar.png', class: "img-circle border-green" %>
                                      <% end %>
                                      <div class="inbox-avatar-text hidden-xs hidden-sm">
                                          <div class="avatar-name"><%= current_user.full_name %></div>
                                          <div><small>Mailbox</small></div>
                                      </div>
                                  </div>
                              </div>
                              <div class="col-xs-8">
                                  <div class="inbox-toolbar btn-toolbar">
                                      <div class="btn-group">
                                          <a href="mailbox.html" class="btn btn-default"><span class="fa fa-long-arrow-left"></span></a>
                                          <a href="" class="hidden-xs hidden-sm btn btn-default"><span class="fa fa-reply-all"></span></a>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="mailbox-body">
                          <div class="row m-0">
                              <div class="col-sm-3 p-0 inbox-nav hidden-xs hidden-sm">
                                  <div class="mailbox-sideber">
                                      <div class="profile-usermenu">
                                          <h6>Mailbox</h6>
                                          <%= render 'mailbox/inbox_nav' %>
                                      </div>
                                  </div>
                              </div>
                              <div class="col-xs-12 col-sm-12 col-md-9 p-0 inbox-mail p-20">
                                <%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
                                    <div class="form-group">
                                      <%= f.label :recipients %>
                                      <%= f.select(:recipients, User.all.collect {|p| [ p.full_name, p.id ] }, {}, { multiple: false , class: "form-control" })%>
                                    </div>
                                    <div class="form-group">
                                      <%= f.label :subject %>
                                      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
                                    </div>
                                    <div id="summernote">
                                      <%= f.label :message %>
                                      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 10  %>
                                    </div>

                                    <div class="btn-group pull-right">
                                      <%= f.submit "SEND", class: "btn btn-success" %>
                                    </div>
                                <% end %>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </section> <!-- /.content -->
  </div>
</div>


<!-- <script>
  "use strict"; // Start of use strict
  //summernote
  $('#summernote').summernote({
      height: 200, // set editor height
      minHeight: null, // set minimum height of editor
      maxHeight: null, // set maximum height of editor
      focus: true                  // set focus to editable area after initializing summernote
  });
</script> -->

app/views/conversations/show.html.erb
<div class="wrapper">
  <%= render 'mailbox/header' %>
    <div class="content-wrapper">
      <%= render 'layouts/content_header' %>
        <section class="content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="mailbox">
                        <div class="mailbox-header">
                            <div class="row">
                                <div class="col-xs-4">
                                    <div class="inbox-avatar">
                                      <% if current_user.picture_url != "" %>
                                        <img class="img-circle border-green" src="<%= current_user.picture_url %>">
                                      <% else %>
                                        <%= image_tag 'avatar.png', class: "img-circle border-green" %>
                                      <% end %>
                                        <div class="inbox-avatar-text hidden-xs hidden-sm">
                                            <div class="avatar-name"><%= current_user.full_name %></div>
                                            <div><small>Mailbox</small></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-8">
                                    <div class="inbox-toolbar btn-toolbar">
                                        <div class="btn-group">
                                            <%= link_to( new_conversation_path, class: "btn btn-success" ) do %>
                                              <span class="fa fa-pencil-square-o make-white"></span>
                                            <% end %>
                                        </div>
                                        <div class="hidden-xs hidden-sm btn-group">
                                          <% if conversation.is_trashed?(current_user) %>
                                              <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
                                          <% else %>
                                              <%= link_to( trash_conversation_path( conversation ), class: 'btn btn-danger', method: :post ) do %>
                                                <span class='fa fa-trash make-white'></span>
                                              <% end %>
                                          <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="mailbox-body">
                            <div class="row m-0">
                                <div class="col-sm-3 p-0 inbox-nav hidden-xs hidden-sm">
                                    <div class="mailbox-sideber">
                                        <div class="profile-usermenu">
                                            <h6>Mailbox</h6>
                                            <% if @receipts.first.trashed %>
                                              <%= render 'mailbox/trash_nav' %>
                                            <% elsif @tagger %>
                                              <%= render 'mailbox/sent_nav' %>
                                            <% else %>
                                              <%= render 'mailbox/inbox_nav' %>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-9 p-0 inbox-mail">
                                    <div class="inbox-avatar p-20 border-btm">
                                      <% last_sender = conversation.messages.sort_by { |message| message.created_at }.last.sender %>
                                      <% other_sender = conversation.recipients.select { |obj| obj != last_sender }.first %>

                                      <% if last_sender.picture_url != "" %>
                                        <img class="border-green hidden-xs hidden-sm" src="<%= last_sender.picture_url %>">
                                      <% else %>
                                        <%= image_tag 'avatar.png', class: "border-green hidden-xs hidden-sm" %>
                                      <% end %>
                                        <div class="inbox-avatar-text">
                                            <div class="avatar-name"><strong>From: <%= last_sender.full_name %></strong>
                                            </div>
                                            <div><small><strong>To: </strong><%= other_sender.full_name %></small></div>
                                            <div><small><strong>Subject: </strong><%= conversation.subject %></small></div>
                                        </div>
                                    </div>
                                    <div class="inbox-mail-details p-20">
                                        <% @receipts.each do | receipt | %>
                                          <% if current_user.full_name == User.find( receipt.message.sender_id ).full_name %>
                                            <div class="border-message-me">
                                          <% else %>
                                            <div class="border-message-recipient">
                                          <% end %>
                                              <h3><%= User.find( receipt.message.sender_id ).full_name %></h3>
                                              <p><%= receipt.message.body %></p>
                                            </div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                            <div class="m-t-20 border-all p-20">
                              <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
                              <div class="form-group">
                                <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
                              </div>
                              <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
                              <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section> <!-- /.content -->
    </div> <!-- /.content-wrapper -->
</div> <!-- ./wrapper -->