config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'dashboard#index'

  resources :contact, :ticket
  resources :users, :items

  resources :projects
  resources :eworker
  resources :csvlocations



  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  get "/dl" => "ticket#dl", as: :download

  get '/slack' => "slack#index"

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/csvlocation.rb
class Csvlocation < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  has_many :links
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
  has_many :items
  has_many :links
  has_many :projects
  has_many :csvlocations

  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ticket_number = Ticket.last.ticket_number.to_i + 1
    @ticket_number = @ticket_number.to_s
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @unread = mailbox.inbox(:unread => true).count

    if current_user.order_admin
      @items = Item.all.sort_by { |obj| obj.created_at }.reverse
    else
      @items = Item.where( user_id: current_user.id ).sort.reverse
    end
  end

  def new
    @unread = mailbox.inbox(:unread => true).count
    @item = Item.new
  end

  def create
    @item = Item.new( item_params )

    if @item.save
      OrdersMailer.new_order.deliver_now

      redirect_to items_path
    end
  end

  def update
    @item = Item.find( params[ 'id' ] )

    if request.xhr?
      if params[ 'status' ] == 'delete'
        @item.destroy
      elsif params[ 'status' ] == 'Ordered'
        @item.update_attributes( status: "Ordered" )
      end
      redirect_to items_path
    end
  end

    private

    def item_params
      params.require( :item ).permit( :name, :qty, :location, :user_id )
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @unread = mailbox.inbox(:unread => true).count

    if current_user.project_approver
      @projects = Project.order( :id )
    else
      @projects = current_user.projects.order( :id )
    end
  end

  def new
    @unread = mailbox.inbox(:unread => true).count
    @project = Project.new()
  end

  def create
    @project = Project.new( create_project_params )

    if @project.save
      NotifyLidiyaMailer.new_notification.deliver_now
      redirect_to projects_path
    end
  end

  def edit
    @project = Project.find( params[ "id" ] )

    if request.xhr?
      if params[ "status" ] == "Approve"
        @project.update_attributes( approved: true )
        render partial: "projects/approved", layout: false, locals: { id: params[ "id" ] }
      else
        @project.update_attributes( approved: false )
        render partial: "projects/denied", layout: false, locals: { id: params[ "id" ] }
      end
    end
  end


    private

      def create_project_params
        params.require( :project ).permit( :user_id, :location, :title, :description )
      end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end

  def find_me( email )
    me = USERS.select { |obj| obj[ 'profile' ][ 'email' ] == email }

    if me.empty?
      return false
    else
      my_picture = me.first[ 'profile' ][ 'image_192' ]
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/csvlocation_helper.rb
module CsvlocationHelper
end

app/helpers/csvlocations_helper.rb
module CsvlocationsHelper
end

app/helpers/eworker_helper.rb
module EworkerHelper
  def compare_pb
    billing_ndc_duplicates = {}
    purchasing_ndc_duplicates = {}
    found = {}

    CSV.foreach( 'billing.csv', headers:true, :header_converters=> lambda { | f | f.strip }, :converters=> lambda { | f | f ? f.strip : nil } ) do | billing |
      if billing[ "CLASS" ].to_i > 0
        if billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ]
          billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ][ 5 ] += billing[ "QUANT" ].to_i
          billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ][ 4 ] += billing[ "TotalInsPaid" ].to_f
        else
          billing_ndc_duplicates[ billing[ "NDC" ].gsub( '-', '' ) ] = [ billing[ "DRGNAME" ], billing[ "DRUGSTRONG" ], billing[ "PACKAGESIZE" ], billing[ "CLASS" ], billing[ "TotalInsPaid" ].to_f, billing[ "QUANT" ].to_i ]
        end
      end
    end

    billing_ndc_duplicates.each { | k,v | v[ 4 ] = v[ 4 ].round( 2 ) }


    CSV.foreach( 'purchasing.csv', headers:true, :header_converters=> lambda { | f | f.strip }, :converters=> lambda { | f | f ? f.strip : nil } ) do | purchasing |
      if purchasing_ndc_duplicates[ purchasing[ "Universal Ndc #" ] ]
        purchasing_ndc_duplicates[ purchasing[ "Universal Ndc #" ] ][ 3 ] += purchasing[ "Quantity Billed" ].to_i
      else
        purchasing_ndc_duplicates[ purchasing[ "Universal Ndc #" ] ] = [ purchasing[ "Item Description" ], purchasing[ "Item Type" ], purchasing[ "Size" ].to_i, purchasing[ "Quantity Billed" ].to_i ]
      end
    end

    purchasing_ndc_duplicates.each do | k, v |
      v << v[ 2 ] * v[ 3 ]
      v.delete_at( 2 )
      v.delete_at( 2 )
    end

    billing_ndc_duplicates.each do | ndc, arr |
      purchasing_ndc_duplicates.each do | ndc2, arr2 |
        if ndc.gsub( /(^|[^0-9])0+/, "" ) == ndc2
          complete = arr.insert( 5, arr2[ 2 ] )
          complete = complete.insert( 0, ndc )
          found[ ndc ] = complete
        end
      end
    end

    CSV.open( "file.csv", "wb", :write_headers=> true, :headers => [ "NDC", "Drug Name", "Drug Strength", "Package Size", "Control", "Total Ins. Paid", "Total Units Purchased", "Total Units Billed" ] ) do | csv |
      found.each do | ndc, arr |
        csv << arr
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    # mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/slack_helper.rb
module SlackHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
  def dropbox
    Dropbox::API::Config.app_key = ENV[ "DROPBOX_APP_KEY" ]
    Dropbox::API::Config.app_secret = ENV[ "DROPBOX_SECRET_KEY" ]
    Dropbox::API::Config.mode = "dropbox"
    @client = Dropbox::API::Client.new( :token  => ENV[ "DROPBOX_TOKEN" ], :secret => ENV[ "DROPBOX_SECRET_TOKEN" ] )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_approved.html.erb
<td class="change-status">Approved</td>
<br>
<p><%= id %></p>

app/views/projects/_denied.html.erb
<td class="change-status">Denied</td>
<br>
<p><%= id %></p>

app/views/projects/_header.html.erb
<header class="main-header">
  <%= link_to( root_path, class: "logo" ) do %>
    <span class="logo-lg">
      <%= image_tag "logo.png" %>
    </span>
  <% end %>

  <%= link_to( root_path, class: "logo cure-logo" ) do %>
    <span class="logo-lg">
      <%= image_tag "logo-cure.png" %>
    </span>
  <% end %>
</header>

<aside class="main-sidebar">
    <!-- sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel text-center">
            <div class="image">
              <% if current_user.picture_url != "" %>
                <img class="img-circle" src="<%= current_user.picture_url %>">
              <% else %>
                <%= image_tag "avatar.png", class: 'img-circle' %>
              <% end %>
            </div>
            <div class="info">
                <p><%= current_user.full_name %></p>
                <%= link_to "Change Avatar", edit_user_path( current_user ), class: "change-avatar-link" %>
                <a href="/slack" class="change-avatar-link slack-link">Link Your Slack Avatar</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form> <!-- /.search form -->
        <!-- sidebar menu -->

        <%= render 'projects/nav' %>
    </div> <!-- /.sidebar -->
</aside>

app/views/projects/_nav.html.erb
<ul class="sidebar-menu">
    <li class="header">MAIN NAVIGATION</li>

    <li>
      <%= link_to( root_path ) do %>
        <i class="ti-home"></i> <span>Dashboard</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( mailbox_inbox_path ) do %>
      <i class="ti-email"></i> <span>Mail</span>
      <span class="pull-right-container">
        <% if @unread > 0 %>
        <small class="label pull-right bg-red"><%= @unread %></small>
        <% else %>
        <i class="fa fa-angle-left pull-right"></i>
        <% end %>
      </span>
      <% end %>
    </li>

    <!-- <li>
      <%= link_to( ticket_index_path ) do %>
        <i class="ti-layout"></i> <span>My Tickets</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li> -->

    <li>
      <%= link_to( items_path ) do %>
        <i class="fa fa-globe"></i> <span>Order Supplies</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li class="active">
      <%= link_to( projects_path ) do %>
        <i class="ti-layout"></i> <span>IT Projects</span>
        <span class="pull-right-container">
          <i class=" fa fa-angle-left pull-right "></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( eworker_index_path ) do %>
        <i class="ti-layout"></i> <span>Excel Worker</span>
        <span class="pull-right-container">
          <i class=" fa fa-angle-left pull-right "></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( destroy_user_session_path, :method => 'delete' ) do %>
        <i class="fa fa-sign-out"></i> <span>Log Out</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li class="header">LABELS</li>
    <li><a href="#"><i class="fa fa-circle color-green"></i> <span>Important</span></a></li>
    <li><a href="#"><i class="fa fa-circle color-red"></i> <span>Warning</span></a></li>
    <li><a href="#"><i class="fa fa-circle color-yellow"></i> <span>Information</span></a></li>
</ul>

app/views/projects/_projects_table.html.erb
<table id="example1" class="footable table table-bordered toggle-arrow-tiny" data-page-size="10" data-filter=#filter>
    <thead>
        <tr>
            <th>Project Title</th>
            <th>Requester</th>
            <th>Email</th>
            <th>Location</th>
            <th>Approval Status</th>
            <th>Status of Project</th>
            <% if current_user.project_approver %>
              <th>Admin</th>
            <% end %>
            <th data-hide="all">Description</th>
        </tr>
    </thead>
    <tbody>
      <% @projects.each do | project | %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.user.full_name %></td>
          <td><%= project.user.email %></td>
          <td><%= project.location %></td>
          <% if project.approved %>
            <td class="change-status <%= project.id %>">Approved</td>
          <% else %>
            <% if project.updated_at > project.created_at %>
              <td class="change-status <%= project.id %>">Denied</td>
            <% else %>
              <td class="change-status <%= project.id %>">In Review</td>
            <% end %>
          <% end %>
          <td></td>
          <% if current_user.project_approver %>
            <td>
              <span>
                <%= link_to( "Approve", edit_project_path( project ), class: "approve-project #{ project.id }" ) %> | <%= link_to( "Deny", edit_project_path( project ), class: "approve-project #{ project.id }" ) %>
              </span>
            </td>
          <% end %>
          <td>
            <p>
              <%= raw project.description %>
            </p>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="6">
                <ul class="pagination pull-right"></ul>
            </td>
        </tr>
    </tfoot>
</table>

app/views/projects/index.html.erb
<!-- Site wrapper -->
<div class="wrapper">
    <%= render 'projects/header' %>

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <%= render 'layouts/content_header' %>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-sm-12">
                  <div class='ct-link'>
                    <%= link_to '+ New Project', new_project_path %>
                  </div>
                    <div class="panel panel-bd lobidrag">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h4>Filter</h4>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <input type="text" class="form-control input-sm m-b-15" id="filter" placeholder="Search in table">
                                <%= render 'projects_table' %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section> <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
</div>

<script>
  "use strict"; // Start of use strict

  // Footable example 2
  $('#example1').footable();

  $( ".approve-project" ).on( "click", function( e ) {
    e.preventDefault();

    var url = e.target.href
    var data = "status=" + e.target.innerText + "&id=" + e.target.className.replace( /^\D+/g, '' )

    $.ajax({
      method: "get",
      url: url,
      data: data
    }).done( function( response ) {
      var text = response.split( "<br>" )[ 0 ].trim();
      var idHTML = response.split( "<br>" )[ 1 ].trim();
      var id = $( idHTML ).text();
      var className = "change-status " + id;

      var changeElement = document.getElementsByClassName( className )[ 0 ];
      changeElement.innerHTML = $( text ).html();
    });
  });
</script>

app/views/projects/new.html.erb
<!-- Site wrapper -->
<div class="wrapper">
  <%= render 'projects/header' %>

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <%= render 'layouts/content_header' %>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-bd lobidrag">
                        <div class="panel-heading">
                            <div class="panel-title issue-heading">
                                <h4>Give a few details about the project!</h4>
                            </div>
                        </div>
                        <div class="panel-body">
                          <%= form_for @project, :url => '/projects', :enctype =>"multipart/form-data" do |f| %>
                            <div class="form-group">
                              <%= f.hidden_field :user_id, value: current_user.id %>
                              <label for="title">Title of Project</label>
                              <%= f.text_field :title, placeholder: "Ex. Convert all Docs into fillable PDF copies" %>
                              <br>
                              <label for="description">Description of Project</label>
                              <%= f.text_area :description, id: 'some-textarea', class: "form-control", rows: "15", placeholder: "Enter text ..." %>
                              <br>
                              <label for="location">Choose a Location</label>
                              <%= f.select :location, [
                                                        [ 'Corporate Office' ],
                                                        [ 'Coney Island Branac' ],
                                                        [ 'Bedstuy' ],
                                                        [ '1413' ],
                                                        [ 'Blondell' ],
                                                        [ 'Audubon' ],
                                                        [ '96th St.' ],
                                                        [ 'Columbus' ],
                                                        [ 'Lexington Ave.' ],
                                                        [ '2nd Ave.' ],
                                                        [ 'Huntington' ],
                                                        [ 'CUC-Huntington' ],
                                                        [ 'CUC-Upper East Side' ],
                                                        [ 'CUC-Upper West Side' ] ]
                                                        %>
                            <br>
                            <%= f.submit 'Submit', class: "btn btn-primary submit-project" %>
                            </div>
                          <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </section> <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
</div>

<script>
    "use strict"; // Start of use strict
    //bootstrap-wysihtml5
    $('#some-textarea').wysihtml5();
</script>