config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'dashboard#index'

  resources :contact, :ticket
  resources :users, :items

  resources :projects
  resources :eworker
  resources :csvlocations



  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  get "/dl" => "ticket#dl", as: :download

  get '/slack' => "slack#index"

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  has_many :links
end

app/controllers/ticket_controller.rb
class TicketController < ApplicationController
  before_action :authenticate_user!
  include TicketHelper

  def index
    # SDK.search('/', Ticket.last.filename)[0]["path"]
    @unread = mailbox.inbox(:unread => true).count

    if current_user.admin
      @tickets = Ticket.order( :id )
    else
      @tickets = current_user.tickets.order( :id )
    end
  end

  def new
    @unread = mailbox.inbox(:unread => true).count
    @ticket = Ticket.new
    @ticket_number = Ticket.all.length + 1
  end

  def create
    ticket = Ticket.new( ticket_params )

    files = params[:ticket].select { |obj, l| obj.include? "uploaded" }
    
    if !files.empty?
      ticket.save

      files.each do | k,v |
        file = v
        Link.create( filename: file.original_filename, ticket_id: ticket.id, user_id: current_user.id )
        dropbox.upload file.original_filename, file.tempfile
      end
    else
      ticket.save
    end

    redirect_to ticket_index_path
  end

  def edit
    if request.xhr?
      if current_user.full_name.downcase == 'elan kvitko'
        @ticket = Ticket.find_by( ticket_number: params[ 'id' ] )
        @ticket.update_attributes( viewed: true )
      end
    else
      @ticket = Ticket.find( params[ 'id' ] )
      @ticket.update_attributes( status: 'Complete' )
      redirect_to ticket_index_path
    end
  end

  def update
    ticket = Ticket.find( params[ :ticket ][ :ticket_id ] )
    file = params[ :ticket ][ :upload ]

    Link.create( filename: file.original_filename, ticket_id: ticket.id, user_id: current_user.id )
    dropbox.upload file.original_filename, file.tempfile

    dl_search = SDK.search( '/', file.original_filename )[ 0 ][ "path" ]
    path = SDK.media( dl_search )[ "url" ]

    FilesMailer.new_file_notification( file.original_filename, path, ticket.user.full_name, ticket.user.email  ).deliver_now

    redirect_to ticket_index_path
  end

  def dl
    if request.xhr?
      ticket = Ticket.find( params[ "ticket" ] )
      dl_search = SDK.search( '/', params[ "dl" ] )[ 0 ][ "path" ]
      path = SDK.media( dl_search )[ "url" ]

      render partial: 'js_response', layout: false, locals: { url: path, ticket_number: ticket.id }
    end
  end

    private

    def ticket_params
      params.require( :ticket ).permit( :user_id, :location, :ticket_number, :body )
    end
end

app/helpers/ticket_helper.rb
module TicketHelper
  def dropbox
    Dropbox::API::Config.app_key = ENV[ "DROPBOX_APP_KEY" ]
    Dropbox::API::Config.app_secret = ENV[ "DROPBOX_SECRET_KEY" ]
    Dropbox::API::Config.mode = "dropbox"
    @client = Dropbox::API::Client.new( :token  => ENV[ "DROPBOX_TOKEN" ], :secret => ENV[ "DROPBOX_SECRET_TOKEN" ] )
  end
end

app/views/ticket/_header.html.erb
<header class="main-header">
  <%= link_to( root_path, class: "logo" ) do %>
    <span class="logo-lg">
      <%= image_tag "logo.png" %>
    </span>
  <% end %>

  <%= link_to( root_path, class: "logo cure-logo" ) do %>
    <span class="logo-lg">
      <%= image_tag "logo-cure.png" %>
    </span>
  <% end %>
</header>

<aside class="main-sidebar">
    <!-- sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel text-center">
            <div class="image">
              <% if current_user.picture_url != "" %>
                <img class="img-circle" src="<%= current_user.picture_url %>">
              <% else %>
                <%= image_tag "avatar.png", class: 'img-circle' %>
              <% end %>
            </div>
            <div class="info">
                <p><%= current_user.full_name %></p>
                <%= link_to "Change Avatar", edit_user_path( current_user ), class: "change-avatar-link" %>
                <a href="/slack" class="change-avatar-link slack-link">Link Your Slack Avatar</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form> <!-- /.search form -->
        <!-- sidebar menu -->

        <%= render 'ticket/nav' %>
    </div> <!-- /.sidebar -->
</aside>

app/views/ticket/_js_response.html.erb
<a href="<%= url %>" download="FileName" target="_blank" id="click_download" class="<%= ticket_number %>">Download it!</a>

app/views/ticket/_nav.html.erb
<ul class="sidebar-menu">
    <li class="header">MAIN NAVIGATION</li>

    <li>
      <%= link_to( root_path ) do %>
        <i class="ti-home"></i> <span>Dashboard</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( mailbox_inbox_path ) do %>
      <i class="ti-email"></i> <span>Mail</span>
      <span class="pull-right-container">
        <% if @unread > 0 %>
        <small class="label pull-right bg-red"><%= @unread %></small>
        <% else %>
        <i class="fa fa-angle-left pull-right"></i>
        <% end %>
      </span>
      <% end %>
    </li>

    <!-- <li class="active">
      <%= link_to( ticket_index_path ) do %>
        <i class="ti-layout"></i> <span>My Tickets</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li> -->

    <li>
      <%= link_to( items_path ) do %>
        <i class="fa fa-globe"></i> <span>Order Supplies</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( projects_path ) do %>
        <i class="ti-layout"></i> <span>IT Projects</span>
        <span class="pull-right-container">
          <i class=" fa fa-angle-left pull-right "></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( eworker_index_path ) do %>
        <i class="ti-layout"></i> <span>Excel Worker</span>
        <span class="pull-right-container">
          <i class=" fa fa-angle-left pull-right "></i>
        </span>
      <% end %>
    </li>

    <li>
      <%= link_to( destroy_user_session_path, :method => 'delete' ) do %>
        <i class="fa fa-sign-out"></i> <span>Log Out</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
      <% end %>
    </li>

    <li class="header">LABELS</li>
    <li><a href="#"><i class="fa fa-circle color-green"></i> <span>Important</span></a></li>
    <li><a href="#"><i class="fa fa-circle color-red"></i> <span>Warning</span></a></li>
    <li><a href="#"><i class="fa fa-circle color-yellow"></i> <span>Information</span></a></li>
</ul>

app/views/ticket/_table.html.erb
<table id="example1" class="footable table table-bordered toggle-arrow-tiny" data-page-size="10" data-filter=#filter>
    <thead>
        <tr>
            <th>Ticket Number</th>
            <th>Name</th>
            <th>Email</th>
            <th>Location</th>
            <th>Status</th>
            <th data-hide="all">Issue</th>
        </tr>
    </thead>
    <tbody>
      <% @tickets.each do | ticket | %>
        <tr class='view-change'>
            <td><%= ticket.ticket_number %></td>
            <td><%= ticket.user.full_name %></td>
            <td><%= ticket.user.email %></td>
            <td><%= ticket.location %></td>
            <td><%= ticket.status %></td>
            <td class="download-td">
              <%= raw( ticket.body ) %>
              <% if !ticket.links.empty? %>
                <br>
                <br>
                <% sent_tickets = ticket.links.select { | link | link.user.full_name != 'Elan Kvitko' } %>
                <% received_tickets = ticket.links.select { | link | link.user.full_name == 'Elan Kvitko' } %>

                <% if !sent_tickets.empty? %>
                  <h4 class="files-head">Sent Files:</h4>

                  <% sent_tickets.each_with_index do | link, idx | %>
                    <%= link_to "Download - #{ link.filename }", download_path, id: ticket.id, class: 'download_path' %>
                    <% if idx != ticket.links.length - 1 %>
                      <br>
                    <% end %>
                  <% end %>
                <% end %>

                <% if !received_tickets.empty? %>
                  <br>
                  <h4 class="files-head">Received Files:</h4>

                  <% received_tickets.each_with_index do | link, idx | %>
                    <%= link_to "Download - #{ link.filename }", download_path, id: ticket.id, class: 'download_path' %>
                    <% if idx != ticket.links.length - 1 %>
                      <br>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>

              <% if current_user.admin %>
                <br>
                <br>
                <%= form_for ticket do |f| %>
                  <%= f.hidden_field :user_id, value: ticket.user.id %>
                  <%= f.hidden_field :ticket_id, value: ticket.id %>
                  <%= f.file_field :upload, class: "form-control" %>
                  <%= f.submit "Submit File" %>
                <% end %>
                <%= link_to "Mark Complete", edit_ticket_path( ticket ) %>
              <% end %>
            </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="6">
                <ul class="pagination pull-right"></ul>
            </td>
        </tr>
    </tfoot>
</table>

app/views/ticket/index.html.erb
<!-- Site wrapper -->
<div class="wrapper">
    <%= render 'ticket/header' %>

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <%= render 'layouts/content_header' %>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-sm-12">
                  <div class='ct-link'>
                    <%= link_to '+ Create A Ticket', new_ticket_path %>
                  </div>
                    <div class="panel panel-bd lobidrag">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h4>Filter</h4>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <input type="text" class="form-control input-sm m-b-15" id="filter" placeholder="Search in table">
                                <%= render 'table' %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section> <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
</div>

<script>
  "use strict"; // Start of use strict

  // Footable example 2
  $('#example1').footable();

  $( 'tr.view-change' ).on( 'click', function( e ) {
    var child = $( e.target.parentElement ).children()[ 0 ]
    var stringy = $( child ).html();
    var ticket_number = parseInt(stringy.replace(/[^0-9\.]/g, ''), 10).toString();
    var url = "/ticket/" + ticket_number + "/edit"
    var type = 'get'
    var data = "viewed=true"

    $.ajax({
      type: type,
      url: url,
      data: data
    }).done( function( response ) {
      return true
    });
  });

  $( '.download_path' ).on( 'click', function( e ) {
    e.preventDefault();

    var url = e.target.href;
    var data = "dl=" + e.target.innerHTML.substring( 11, e.target.innerHTML.length ) + "&ticket=" + e.target.id

    $.ajax({
      type: 'get',
      url: url,
      data: data
    }).done( function( response ) {
      var tag = $( response )[ 0 ];
      tag.click();
    });
  });
</script>

app/views/ticket/new.html.erb
<!-- Site wrapper -->
<div class="wrapper">
  <%= render 'ticket/header' %>

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <%= render 'layouts/content_header' %>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-bd lobidrag">
                        <div class="panel-heading">
                            <div class="panel-title issue-heading">
                                <h4>What is your issue?</h4>
                            </div>
                        </div>
                        <div class="panel-body">
                          <%= form_for @ticket, :url => '/ticket', :enctype =>"multipart/form-data" do |f| %>
                            <div class="form-group">
                              <%= f.hidden_field :user_id, value: current_user.id %>
                              <%= f.hidden_field :ticket_number, value: @ticket_number %>
                              <%= f.text_area :body, id: 'some-textarea', class: "form-control", rows: "15", placeholder: "Enter text ..." %>
                              <br>
                              <div class="file-upload-fields">
                                <%= f.file_field :uploaded_0 %>
                              </div>
                              <br>
                              <button type="button" name="button" class="add-file">Add Another File</button>
                              <br>
                              <label for="location">Choose a Location</label>
                              <%= f.select :location, [
                                                        [ 'Corporate Office' ],
                                                        [ 'Coney Island Branac' ],
                                                        [ 'Bedstuy' ],
                                                        [ '1413' ],
                                                        [ 'Blondell' ],
                                                        [ 'Audubon' ],
                                                        [ '96th St.' ],
                                                        [ 'Columbus' ],
                                                        [ 'Lexington Ave.' ],
                                                        [ '2nd Ave.' ],
                                                        [ 'Huntington' ],
                                                        [ 'CUC-Huntington' ],
                                                        [ 'CUC-Upper East Side' ],
                                                        [ 'CUC-Upper West Side' ] ]
                                                        %>
                            <br>
                            <%= f.submit 'Submit', class: "btn btn-primary submit-issue" %>
                            </div>
                          <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </section> <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
</div>

<script>
    "use strict"; // Start of use strict
    //bootstrap-wysihtml5
    $('#some-textarea').wysihtml5();

    var idx = 1

    $( 'button.add-file' ).on( 'click', function( e ) {
      var div = document.getElementsByClassName( 'file-upload-fields' )[ 0 ];
      $( div ).append( "<input type='file' name='ticket[uploaded_" + idx + "]' id='ticket_uploaded_" + idx + "'>" );
      idx += 1
    });
</script>